ccflags-y += -Idrivers/media/platform/msm/camera_v2/
ccflags-y += -Idrivers/misc/
obj-$(CONFIG_MSMB_CAMERA) += msm_camera_io_util.o cam_smmu_api.o cam_hw_ops.o cam_soc_api.o msm_camera_tz_util.o
obj-$(CONFIG_MACH_NOKIA_SDM439) += nokia_sdm439_camera_vars.o
